# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "admin-extension"
client_id = "5652cbbbeaedfc5504ffe08fca78ef76"
application_url = "https://admin-extension--development.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://admin-extension--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "checkout-branding-testing.myshopify.com"
